### ISSUE TITLE
GCP: NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:postgresql.psycopg exception

### ISSUE THREAD

**Issue by bono-mp** [bengen343/superset-on-gcp-cloud-run#1] opened 2022-07-04 08:02 UTC
Hey, 

When I try to access my deployed suerpset instance on GCP I get following error: 

"Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/superset/app.py", line 37, in create_app
    app_initializer.init_app()
  File "/usr/local/lib/python3.8/site-packages/superset/initialization/__init__.py", line 567, in init_app
    self.setup_db()
  File "/usr/local/lib/python3.8/site-packages/superset/initialization/__init__.py", line 693, in setup_db
    pessimistic_connection_handling(db.engine)
  File "/usr/local/lib/python3.8/site-packages/flask_sqlalchemy/__init__.py", line 998, in engine
    return self.get_engine()
  File "/usr/local/lib/python3.8/site-packages/flask_sqlalchemy/__init__.py", line 1017, in get_engine
    return connector.get_engine()
  File "/usr/local/lib/python3.8/site-packages/flask_sqlalchemy/__init__.py", line 594, in get_engine
    self._engine = rv = self._sa.create_engine(sa_url, options)
  File "/usr/local/lib/python3.8/site-packages/flask_sqlalchemy/__init__.py", line 1027, in create_engine
    return sqlalchemy.create_engine(sa_url, **engine_opts)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/__init__.py", line 525, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/strategies.py", line 61, in create
    entrypoint = u._get_entrypoint()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/url.py", line 172, in _get_entrypoint
    cls = registry.load(name)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 277, in load
    raise exc.NoSuchModuleError(
sqlalchemy.exc.NoSuchModuleError: Can't load plugin: `sqlalchemy.dialects:postgresql.psycopg"

There seems to be a python version mismatch, However, I have not been able to solve it. I haven't got much experience with GCP so currently I am able to tell whether it is related to the python version on GCP or the container.

**Comment by Innarticles** [comment] 2022-07-14 15:59
@bono-mp did you get resolving this?
Having the same issue.

**Comment by bono-mp** [comment] 2022-07-15 13:00
> @bono-mp did you get resolving this? Having the same issue.

I had no succes, although I haven't had any time to really look into it.

**Comment by bcoffee** [comment] 2022-09-17 15:36
Having the same issue.

**Comment by lord-skinner** [comment] 2022-10-18 19:50
Same issue

**Comment by lord-skinner** [comment] 2022-10-28 20:20
Hello friends. After much pounding of sand I was able to get passed this error. I finally noticed that the error was loading `sqlalchemy.dialects:postgresql.psycopg`, but `psycopg2` was what was being `pip installed` in the requirements.txt file. So I updated the connection string to start with `postgres+psycopg2://` instead of `postgres+psycopg://`.

Changing that actually got me a net new error, but I was at least making progress. Next it started barking at me about not being able to resolve the host in the [example uri](https://github.com/bengen343/superset-on-gcp-cloud-run/blob/1f35f7d1b3213e31c2ea137c6bbd8cb43985fd6c/.env.template#L42) . 

I then went a googling and found that the connection string was malformed a tiny bit. 

Here is an updated version:
```
postgres+psycopg2://<un>:<pwd>@/<db>?host=/cloudsql/<project>:<region>:<db>
```

I was still getting an error, but this time it was something about a unix_sock and I went back to googling. Eventually I ran across an [this stackoverflow post](https://stackoverflow.com/questions/55562098/unable-to-connect-google-app-engine-to-cloudsql-postgres-via-sqlalchemy-in-clo). I read through this and gave it a shot.

I commented out [this line](https://github.com/bengen343/superset-on-gcp-cloud-run/blob/1f35f7d1b3213e31c2ea137c6bbd8cb43985fd6c/src/superset_config.py#L8) and set an environment variable in my container for  `SQLALCHEMY_DATABASE_URI` as the updated connection sting and bingo.

My next step is to update the `gcloud run deploy` [command](https://github.com/bengen343/superset-on-gcp-cloud-run/blob/1f35f7d1b3213e31c2ea137c6bbd8cb43985fd6c/setup-scripts/create_gcp_cloud_run.sh#L9) to insert the connection string as an environment variable named `SQLALCHEMY_DATABASE_URI` and retest deploying to cloud run. I'll update this post once I have finished testing.

Hope this helps someone.

thx @lord-skinner

**Comment by lord-skinner** [comment] 2022-10-28 20:39
Welp it didn't give me errors when running locally in a container, but once I deployed I noticed it was attempting to work off a sqlite database so it looks like it's just defaulting to that with no explicit var in the setup_config.py 🤔

**Comment by bono-mp** [comment] 2022-11-02 08:51
@lord-skinner , thx for looking into this. I'm picking this up again. I'll report one I've made progress.

**Comment by ericdrosas87** [comment] 2022-11-02 22:28
@bono-mp I encountered this error and I had to drop the `+psycopg` part from the connection string, then the host name couldn't be resolved, so I went into the GCP web console and found the private IP for my DB instance and replaced the whole  `superset?host=<long string>` part of the end of the connection string with the private IP and that got me passed the error.

**Comment by aboudzein** [comment] 2022-11-23 07:35
I've done as you said @ericdrosas87 , and it's working  , just want to mention that I've used vpc serverless connection to connect to the private cloud sql instance .

**Comment by ohitsdoh** [comment] 2022-12-13 12:46
Just want to note that @ericdrosas87's solution works great, but a VPC network is necessary to get it going!

**Comment by bengen343** [comment] 2022-12-23 18:08
Thank you all for looking into this. I'm sorry I haven't had time to return to this for so long. As some folks have noted the root of the error was in a type in this line. I've updated the repository with a correction.
`SUPERSET_CONNECTION_SECRET=postgresql+psycopg2://superset:<SQL_PASSWORD>@/superset?host=/cloudsql/apache-superset-350214:us-west1:superset-configs`

**Closed as completed by bengen343** 2022-12-23 18:08 UTC

**Comment by vkt1414** [comment] 2022-12-25 01:38
Hi all, I'm still facing the issue. Could anyone help me troubleshoot? thank you very much. 
![image](https://user-images.githubusercontent.com/115020590/209454748-60168337-98b2-4697-9805-498e6915f00a.png)

**Comment by bengen343** [comment] 2022-12-25 09:28
@vkt1414 The error you're showing is caused by a separate issue. It appears to be a problem with the actual database you've set up to drive Superset. I recommend attempting to run the `superset db upgrade` command again from your VS Code dev container as in [this step](https://github.com/bengen343/superset-on-gcp-cloud-run#build-superset-configuration-sql-database).

**Comment by vkt1414** [comment] 2022-12-27 20:28
thanks so much for your response. I think I was blindly following the setup instructions. I was not able to make it work from this repo yet (i'm going to give more tries and try to fix some dependencies), but when you mentioned db upgrade, it got me thinking that we are using the dev container just to make sure the superset metadata database is populated and is ready to go when we deploy the same image in cloud run. So I used my bread-and-butter mysql database as backend, and deployed a container locally and did superset db upgrade and init.  I then used exact same config to build an image on gcp, then used it run on cloud run and it worked! thanks again for sharing the knowledge and making this repo!
